### ISSUE TITLE
Keyboard input not working

### ISSUE THREAD

**Issue by fiermanb** [MiSTer-devel/Arcade-Galivan_MiSTer#1] opened 2022-09-17 18:01 UTC
From within the core, I can remap the game inputs to both keyboard and controllers/joysticks.

When in game however, the keyboard inputs are not registered afterwards. Using a keyboard for coin/start for instance is thus not possible.

**Comment by pcornier** [comment] 2022-09-17 21:32
Thanks for reporting. Yes, keyboard is not done yet. I'm adding an example of a nice implemention here so I, or anybody else, can refer to it later:
https://github.com/MiSTer-devel/Arcade-Cave_MiSTer/blob/8f46b818f9e2d2996be38cf55c8c22b2917d0c64/quartus/cave.sv#L395

**Comment by pcornier** [comment] 2022-09-18 16:31
I will push a fix tomorrow. The problem is just a missing line in CONF_STRING.

**Comment by pcornier** [comment] 2022-09-19 11:58
I was able to map keyboard keys now with latest release. I let you check and close (or comment). Thank you.

**Comment by fiermanb** [comment] 2022-09-19 13:19
Thank you for all your work.
I tried out the new build briefly, and keyboard inputs are functional now. 

There are a few minor glitches with it: dipswitch settings for coins are not translated well to keypresses (1c/c is interpreted as 2c for instance) ; and the keys for coin 2 and start 2 are not registered to the mapped keys, but to other keys instead. I suppose that can be fixed in the .mra files?

**Comment by pcornier** [comment] 2022-09-20 14:23
Thank you, yes it sounds like problems with the MRA file. I will close this one.

**Closed as completed by pcornier** 2022-09-20 14:23 UTC
